// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class CharLevelTable
{
    public int char_level;
    public float char_stat_growth;
    public float char_exp_limit;
}
