// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class Bathhouse
{
    public int bathhouse_gradeid;
    public int bathhouse_id;
    public string is_unlocked;
    public int bathhouse_cost;
    public int bathhouse_time;
    public float bathhouse_goldinterest;
    public int bathhouse_maxgold;
    public float bathhouse_energyinterest;
    public int bathhouse_maxcustomer;
}
