// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class Consumable
{
    public int consumable_group;
    public int consumable_id;
    public float consumable_chance;
    public int consumable_energyfill;
}
