// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'TypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum TypeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
    Value3 = 3,
}

// TODO: 'ConditionType' 멤버 이름을 실제 값으로 수정하세요.
public enum ConditionType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
}

[Serializable]
public class RelicDivision
{
    public int id;
    public string desc;
    public TypeType type;
    public ConditionType condition;
    public float value;
    public string name;
    public string script;
}
