// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "RelicEnhanceSO", menuName = "Data/RelicEnhanceSO")]
public class RelicEnhanceSO : ScriptableObject
{
    public List<RelicEnhance> dataList = new List<RelicEnhance>();

    public RelicEnhance GetById(int id)
        => dataList.Find(x => x.id == id);
}
