// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'ItemTypeType' 멤버 이름을 실제 값으로 수정하세요.


[Serializable]
public class ItemInventoryTable
{
    public int inven_id;
    public ITEM_TYPE item_type;
    public int item_id;
    public int quantity;
    public int remain_time;
    public int slot_index;
    public string user_id;
}
