// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'ItemTypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum ItemTypeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
    Value3 = 3,
    Value4 = 4,
}

[Serializable]
public class ItemManageTable
{
    public int item_id;
    public string desc;
    public ItemTypeType item_type;
    public int max_stack;
    public int item_name_key;
    public string item_img;
}
