// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

public enum ITEM_CONSUME_TYPE
{
    Enter = 0,
    Exp = 1,
    EnergyUp = 2,
}

[Serializable]
public class ItemConsumeTable
{
    public int item_id;
    public ITEM_CONSUME_TYPE item_stat_type;
    public int item_opt;
    public int item_opt_desc;
    public int item_script;
    public string item_using_after_illust;
}
