// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'ItemStatTypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum ItemStatTypeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
}

[Serializable]
public class ItemConsumeTable
{
    public int item_id;
    public ItemStatTypeType item_stat_type;
    public int item_opt;
    public int item_opt_desc;
    public int item_script;
    public string item_using_after_illust;
}
