// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "MonsterDropSO", menuName = "Data/MonsterDropSO")]
public class MonsterDropSO : ScriptableObject
{
    public List<MonsterDrop> dataList = new List<MonsterDrop>();

    public MonsterDrop GetById(int id)
        => dataList.Find(x => x.drop_group_id == id);
}
