// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class MonsterResource
{
    public int resource_id;
    public string index;
    public string move_animation;
    public string cast_animation;
    public string attack_animation;
    public string death_animation;
    public string attack_effect;
}
