// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "MonsterSO", menuName = "Data/MonsterSO")]
public class MonsterSO : ScriptableObject
{
    public List<Monster> dataList = new List<Monster>();

    public Monster GetById(int id)
        => dataList.Find(x => x.monster_id == id);
}
