// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'MonsterTypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum MonsterTypeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
    Value3 = 3,
}

[Serializable]
public class Monster
{
    public int monster_id;
    public string index;
    public MonsterTypeType monster_type;
    public int pattern_group_id;
    public float drop_chance;
    public int drop_group_id;
    public int daily_gold_drop;
    public int drop_resource_id;
    public int resource_id;
}
