// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class PatternGroupComposition
{
    public int pattern_group_id;
    public string index;
    public int pattern_id;
    public float pattern_cooldown;
    public int priority;
}
