// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;


public enum MATTERPART
{
    Weapon = 0,
    Helmet = 1,
    Cloak = 2,
    Shoes = 3
}

// TODO: 'GradeType' 멤버 이름을 실제 값으로 수정하세요.
public enum EQUIPMATTERGRADE
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
    Value3 = 3,
    Value4 = 4,
}

[Serializable]
public class EquipMatter
{
    public int id;
    public string desc;
    public PART part_type;
    public EQUIPMATTERGRADE grade;
    public int max_stack;
    public int cost_id;
    public int cost_count;
    public int price;
    public string name;
    public string script;
    public string sprite;
    public string effect;
    public string sound;
}
