// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class MonsterWaveTable
{
    public int wave_id;
    public string _description;
    public int group_id;
    public int wave_index;
    public int start_time;
    public int end_time;
    public int monster_id;
    public int spawn_amount;
    public int spawn_pattern;
    public int mid_boss_id;
    public float hp_modifier;
    public float power_modifier;
}
