// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class Pattern
{
    public int pattern_id;
    public string index;
    public int pattern_type;
    public string pattern_logic_type;
    public float duration;
    public float cast_time;
    public float cooldown;
    public float pattern_value;
    public float damage_multiply;
    public float detect_range;
    public float move_time;
    public float zigzag_width;
    public float jump_height;
    public float chase_time;
    public int escape_target;
    public float rush_speed;
    public int projectile_type;
    public float projectile_speed;
    public float projectile_size;
    public int projectile_count;
    public float fire_interval;
    public float life_time;
    public int pierce_type;
    public bool follow;
    public float arc_height;
    public float projectile_radius;
    public string area_radius;
    public float area_damage_interval;
    public int area_target_type;
    public float explode_range;
    public int summon_monster_id;
    public int summon_count;
    public float summon_radius;
    public int summon_position_type;
    public int debuff_type;
    public float debuff_duration;
    public float debuff_value;
    public float debuff_damage_interval;
    public int barrier_shape;
    public int barrier_target_type;
    public float barrier_size_x;
    public float barrier_size_y;
    public int anchor_type;
    public float barrier_offset_x;
    public float barrier_offset_y;
    public float barrier_damage;
    public bool barrier_collision_block;
}
