// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class SpecialMonsterTable
{
    public int special_id;
    public string _description;
    public int special_group_id;
    public int spawn_type;
    public int start_time;
    public int end_time;
    public int generation_time;
    public int monster_id;
}
