// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class EquipEnhance
{
    public int id;
    public string desc;
    public int group_id;
    public int level;
    public bool is_max_level;
    public float add_value;
    public int cost_gold;
    public int cost_blueprint;
    public int blueprint_id;
}
