// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'TypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum EQUIP_STAT_TYPE
{
    Attack = 0, //공격력
    CriticalRate = 1, //치명타 확률
    MaxHP = 2, //최대 체력
    Defense = 3, //방어력 
    MoveSpeed = 4, //이동 속도
    Dodge = 5, //회피
}

[Serializable]
public class EquipStat
{
    public int id;
    public string desc;
    public int group_id;
    public EQUIP_STAT_TYPE type;
    public float value;
}
