// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class ExpTable
{
    public int exp_id;
    public int base_exp;
    public int growth_value;
    public int max_cap_level;
}
