// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "ExpTableSO", menuName = "Data/ExpTableSO")]
public class ExpTableSO : ScriptableObject
{
    public List<ExpTable> dataList = new List<ExpTable>();

    public ExpTable GetById(int id)
        => dataList.Find(x => x.exp_id == id);
}
