// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'SpawnPatternType' 멤버 이름을 실제 값으로 수정하세요.
public enum SpawnPatternType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
    Value3 = 3,
}

[Serializable]
public class MonsterWaveTable
{
    public int wave_id;
    public string _description;
    public int group_id;
    public int wave_index;
    public int start_time;
    public int end_time;
    public int monster_id;
    public int spawn_amount;
    public SpawnPatternType spawn_pattern;
    public int mid_boss_id;
    public float hp_modifier;
    public float power_modifier;
    public float exp_multiply;
}
