// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'GradeType' 멤버 이름을 실제 값으로 수정하세요.
public enum GradeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
    Value3 = 3,
    Value4 = 4,
}

[Serializable]
public class RankTable
{
    public int rank_id;
    public int rank_table_id;
    public GradeType grade;
    public int min_score;
    public float reward_multiplier;
}
