// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "RankTableSO", menuName = "Data/RankTableSO")]
public class RankTableSO : ScriptableObject
{
    public List<RankTable> dataList = new List<RankTable>();

    public RankTable GetById(int id)
        => dataList.Find(x => x.rank_id == id);
}
