// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'RewardCategoryType' 멤버 이름을 실제 값으로 수정하세요.
public enum REWARD_CATEGORY
{
    First = 0, //첫 클리어시만 지급
    Always = 1, //항상 지급 
}


public enum REWARD_TYPE
{
    Gold = 0,
    Equipment = 1,
    BluePrint = 2, //도면 
    
}

[Serializable]
public class RewardTable
{
    public int reward_id;
    public int _description;
    public int reward_group_id;
    public REWARD_CATEGORY reward_category;
    public REWARD_TYPE reward_type1;
    public int item_id;
    public int min_count;
    public int max_count;
    public float drop_rate;
}
