// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "RewardTableSO", menuName = "Data/RewardTableSO")]
public class RewardTableSO : ScriptableObject
{
    public List<RewardTable> dataList = new List<RewardTable>();

    public RewardTable GetById(int id)
        => dataList.Find(x => x.reward_id == id);
}
