// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "SpecialMonsterTableSO", menuName = "Data/SpecialMonsterTableSO")]
public class SpecialMonsterTableSO : ScriptableObject
{
    public List<SpecialMonsterTable> dataList = new List<SpecialMonsterTable>();

    public SpecialMonsterTable GetById(int id)
        => dataList.Find(x => x.special_id == id);
}
