// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'SpawnType 멤버 이름을 실제 값으로 수정하세요.
public enum SPAWN_TYPE
{
    Repeat = 0, //일정 간격으로 반복 등장 
    Once = 1, //일회성 등장
    
}

[Serializable]
public class SpecialMonsterTable
{
    public int special_id;
    public string _description;
    public int special_group_id;
    public SPAWN_TYPE spawn_type;
    public int start_time;
    public int end_time;
    public int generation_time;
    public int monster_id;
}
