// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class StageTable
{
    public int stage_id;
    public int tower_id;
    public int stage_index;
    public int main_time;
    public int boss_time;
    public int entry_energy;
    public int monster_group_id;
    public int special_group_id;
    public int boss_id;
    public int reward_group_id;
    public int rank_table_id;
    public float hp_modifier;
    public float power_modifier;
    public int reward_preview;
    public string map_resource;
    public int exp_gain;
}
