// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class TowerTable
{
    public int tower_id;
    public int need_stage_id;
    public float hp_modifier;
    public float power_modifier;
    public string tower_icon_resource;
    public string bgm_resource;
    
}
