// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'TriggerTypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum TriggerTypeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
}

// TODO: 'ActionTypeType' 멤버 이름을 실제 값으로 수정하세요.
public enum ActionTypeType
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
}

[Serializable]
public class TutorialTable
{
    public int tutorial_id;
    public string _description;
    public string tutorial_group_id;
    public int step_id;
    public TriggerTypeType trigger_type;
    public string trigger_id;
    public int trigger_value;
    public ActionTypeType action_type;
    public string action_ui_key;
    public int max_wait_time;
    public string string_key;
}
