// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "TutorialTableSO", menuName = "Data/TutorialTableSO")]
public class TutorialTableSO : ScriptableObject
{
    public List<TutorialTable> dataList = new List<TutorialTable>();

    public TutorialTable GetById(int id)
        => dataList.Find(x => x.tutorial_id == id);
}
