// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

// TODO: 'DungeonType0:주간유물던전Type' 멤버 이름을 실제 값으로 수정하세요.
public enum DUNGEONTYPE
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
}

// TODO: 'Difficulty0:쉬움1:중간2:어려움Type' 멤버 이름을 실제 값으로 수정하세요.
public enum DIFFICULTY
{
    Value0 = 0,
    Value1 = 1,
    Value2 = 2,
}

[Serializable]
public class WeeklyDungeon
{
    public int dungeon_id;
    public string _description;
    public int stage_id;
    public DUNGEONTYPE dungeon_type;
    public DIFFICULTY difficulty;
    public int unlock_req_tower;
    public int max_boss_count;
    public int boss_stat_multi;
    public int per_boss_reward;
    public int max_reward_limit;
}
