// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "WeeklyDungeonSO", menuName = "Data/WeeklyDungeonSO")]
public class WeeklyDungeonSO : ScriptableObject
{
    public List<WeeklyDungeon> dataList = new List<WeeklyDungeon>();

    public WeeklyDungeon GetById(int id)
        => dataList.Find(x => x.dungeon_id == id);
}
