// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "StringSO", menuName = "Data/StringSO")]
public class StringSO : ScriptableObject
{
    public List<String> dataList = new List<String>();

    public String GetById(string id)
        => dataList.Find(x => x.string_id == id);
}
