// Auto-generated by CsvAutoGenerator. Do not edit manually.
using System;

[Serializable]
public class String
{
    public string string_id;
    public string category;
    public string context;
    public string kr;
    public string eng;
    public string jp;
    public string cn;
}
